import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          ScreenSplashScreen(),
        ]),
      ),
    );
  }
}

class ScreenSplashScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.50, -0.00),
              end: Alignment(0.50, 1.00),
              colors: [Color(0xFF738FFE), Color(0xFF2A36B1)],
            ),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(20),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 467.78,
                top: 80.40,
                child: Opacity(
                  opacity: 0.80,
                  child: Container(
                    width: 438.62,
                    height: 117.21,
                    decoration: BoxDecoration(
                      gradient: RadialGradient(
                        center: Alignment(0.09, 0.46),
                        radius: 84.20,
                        colors: [Colors.white.withValues(alpha: 26), Colors.white.withValues(alpha: 0)],
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 480.87,
                top: 244.04,
                child: Opacity(
                  opacity: 0.80,
                  child: Container(
                    width: 391.55,
                    height: 117.21,
                    decoration: BoxDecoration(
                      gradient: RadialGradient(
                        center: Alignment(0.09, 0.46),
                        radius: 84.20,
                        colors: [Colors.white.withValues(alpha: 26), Colors.white.withValues(alpha: 0)],
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 333.18,
                top: 11.08,
                child: Opacity(
                  opacity: 0.80,
                  child: Container(
                    width: 391.55,
                    height: 117.21,
                    decoration: BoxDecoration(
                      gradient: RadialGradient(
                        center: Alignment(0.09, 0.46),
                        radius: 84.20,
                        colors: [Colors.white.withValues(alpha: 26), Colors.white.withValues(alpha: 0)],
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 193,
                top: 418,
                child: Opacity(
                  opacity: 0,
                  child: Container(
                    width: 3.90,
                    height: 8.44,
                    padding: const EdgeInsets.only(
                      top: 0.74,
                      left: 0.24,
                      right: 0.24,
                      bottom: 0.50,
                    ),
                    clipBehavior: Clip.antiAlias,
                    decoration: ShapeDecoration(
                      color: Colors.white /* White */,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(0.20),
                      ),
                    ),
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.end,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      spacing: 0.32,
                      children: [
                        Container(
                          padding: const EdgeInsets.only(top: 0.30, bottom: 0.60),
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.end,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 0.08,
                            children: [
                              Container(
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.symmetric(vertical: 0.07),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Column(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        spacing: 0.07,
                                        children: [
                                        
                                        ],
                                      ),
                                    ),
                                    Container(
                                      child: Column(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.center,
                                        spacing: 0.08,
                                        children: [
                                          Container(
                                            width: 1.51,
                                            height: 0.05,
                                            decoration: BoxDecoration(
                                              color: Color(0xFF00AFB9) /* Primary-MedUP */,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                        Container(
                          height: 2.44,
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.end,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 0.24,
                            children: [
                              Container(
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  spacing: 0.24,
                                  children: [
                                    Container(
                                      child: Column(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.center,
                                        spacing: 0.08,
                                        children: [
                                          SizedBox(
                                            width: 2.75,
                                            child: Text(
                                              'Your Healthcare Journey Starts Here',
                                              textAlign: TextAlign.center,
                                              style: TextStyle(
                                                color: Color(0xFF13151A) /* Text-Black */,
                                                fontSize: 0.24,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w600,
                                                height: 1.33,
                                              ),
                                            ),
                                          ),
                                          SizedBox(
                                            width: 3.11,
                                            child: Text(
                                              'Easily find medical facilities, book appointments, manage your schedule, and track your queue status—all in one place',
                                              textAlign: TextAlign.center,
                                              style: TextStyle(
                                                color: Color(0xFF5E6B81) /* Secondary-Text */,
                                                fontSize: 0.14,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w300,
                                                height: 1.43,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Container(
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.center,
                                        spacing: 0.04,
                                        children: [
                                          Container(
                                            width: 0.24,
                                            height: 0.08,
                                            decoration: ShapeDecoration(
                                              color: Color(0xFF00AFB9) /* Primary-MedUP */,
                                              shape: RoundedRectangleBorder(
                                                borderRadius: BorderRadius.circular(0.04),
                                              ),
                                            ),
                                          ),
                                          Container(
                                            width: 0.08,
                                            height: 0.08,
                                            decoration: ShapeDecoration(
                                              color: Color(0xFFE0E0E3),
                                              shape: OvalBorder(),
                                            ),
                                          ),
                                          Container(
                                            width: 0.08,
                                            height: 0.08,
                                            decoration: ShapeDecoration(
                                              color: Color(0xFFE0E0E3),
                                              shape: OvalBorder(),
                                            ),
                                          ),
                                          Container(
                                            width: 0.08,
                                            height: 0.08,
                                            decoration: ShapeDecoration(
                                              color: Color(0xFFE0E0E3),
                                              shape: OvalBorder(),
                                            ),
                                          ),
                                          Container(
                                            width: 0.08,
                                            height: 0.08,
                                            decoration: ShapeDecoration(
                                              color: Color(0xFFEDEDFC),
                                              shape: OvalBorder(),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                              Container(
                                width: 3.27,
                                padding: const EdgeInsets.all(0.16),
                                clipBehavior: Clip.antiAlias,
                                decoration: ShapeDecoration(
                                  color: Color(0xFF00AFB9) /* Primary-MedUP */,
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(0.14),
                                  ),
                                ),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  spacing: 0.08,
                                  children: [
                                    Text(
                                      'Get Started',
                                      style: TextStyle(
                                        color: Colors.white /* White */,
                                        fontSize: 0.16,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w600,
                                        height: 1.50,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 390,
                  height: 47,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 390,
                          height: 47,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 37,
                                top: 16.05,
                                child: SizedBox(
                                  width: 54.42,
                                  height: 20.15,
                                  child: Text(
                                    '9:41',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.white /* White */,
                                      fontSize: 17.13,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w700,
                                      height: 1.29,
                                      letterSpacing: 0.26,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 329.67,
                                top: 20,
                                child: Container(
                                  width: 27.61,
                                  height: 12.48,
                                  child: Stack(),
                                ),
                              ),
                              Positioned(
                                left: 132,
                                top: 10,
                                child: Container(
                                  width: 125,
                                  height: 36.67,
                                  decoration: ShapeDecoration(
                                    color: Colors.black,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(18.33),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 206.21,
                                top: 18.59,
                                child: SizedBox(
                                  width: 54.42,
                                  height: 20.15,
                                  child: Opacity(
                                    opacity: 0,
                                    child: Text(
                                      '0:26',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Color(0xFFE1A245),
                                        fontSize: 15.80,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                        height: 1.40,
                                        letterSpacing: -0.41,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 230.67,
                                top: 20.67,
                                child: Container(
                                  width: 16,
                                  height: 16,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://placehold.co/16x16"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 192,
                top: 343,
                child: SizedBox(
                  width: 132,
                  height: 159,
                  child: Text(
                    'empowerHealt',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 24.01,
                      fontFamily: 'Metamorphous',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}